#!/bin/bash
cd /app

echo "Installing composer packages"
composer install
 
if [ ! -f .env ]; then
    echo "Creating .env file"
    cp .env.example .env
fi

echo "generating keys"
php artisan key:generate

echo "Running migrations"
php artisan migrate